### ISSUE TITLE
Size is bitwise

### ISSUE THREAD

**Issue by cr1901** [pftbest/msp430_svd#18]
SVDs generated currently a byte-wise size of 2; they need to have a bit-wise size of 16. see also https://github.com/pftbest/msp430g2553/issues/6.

**Comment by pftbest** [comment]
Newer versions of svd-parser have a feature for writing svd. We can remove src/svd_writer.rs file and it will probably fix some other issues too.

**Comment by cr1901** [comment]
This has been fixed. We are now using the [`svd_encoder`](https://github.com/rust-embedded/svd) crate to write SVDs. Looking at the output, the changes compared to the previous internal parser are minimal (and include fields that we omitted).
