### ISSUE TITLE
msp430f2619 trigger panicking at dslite_parser.rs:88:17

### ISSUE THREAD

**Issue by LX3JL** [pftbest/msp430_svd#22]
Attempt to generate an svd for msp430f2619 trigger panicking with following backtarce:

   0: rust_begin_unwind
             at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/core/src/panicking.rs:65:14
   2: msp430gen::dslite_parser::parse_dslite
             at ./src/dslite_parser.rs:88:17
   3: msp430gen::main
             at ./src/main.rs:43:22
   4: core::ops::function::FnOnce::call_once
             at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/core/src/ops/function.rs:251:5

**Comment by LX3JL** [comment]
and the trace output...

OLD Register {
    name: "DMA0SAL",
    description: "DMA Channel 0 Source Address",
    module: "DMA",
    offset: 466,
    width: 2,
    fields: [],
    alternate: None,
}
NEW Register {
    name: "DMA0SA",
    description: "DMA Channel 0 Source Address",
    module: "DMA",
    offset: 466,
    width: 4,
    fields: [],
    alternate: None,
}

**Comment by cr1901** [comment]
Can you please post the exact command line you used to trigger the panic?

**Comment by LX3JL** [comment]
cargo run -- msp430f2619 > msp430f2619.svd

**Comment by cr1901** [comment]
The following patch fixes things on my end, but I'm not 100% sure it's the correct fix:

```diff
diff --git a/src/dslite_parser.rs b/src/dslite_parser.rs
index a1d5604..6e310b5 100644
--- a/src/dslite_parser.rs
+++ b/src/dslite_parser.rs
@@ -57,7 +57,7 @@ pub fn parse_dslite(file_name: &Path) -> Device {
     let mut memory: IndexMap<u32, &Register> = IndexMap::new();
     for r in &registers {
         if let Some(old) = get_conflict(&memory, r) {
-            if r.width == 2 && old.width == 1 {
+            if r.width == 2 && old.width == 1 || r.width == 4 && old.width == 2 {
                 if !memory.contains_key(&r.offset) || !memory.contains_key(&(r.offset + 1)) {
                     eprintln!(
                         "warning: register {} ({}) has missing parts",
```

There's something wrong w/ my `rust-analyzer` setup which is making it effectively impossible to test this properly, so I'm not ready to commit right now.

**Comment by LX3JL** [comment]
Works for me here.
Thanks!
